manifest_version = "0.1.0"
name = "Compute@Edge template for Rust"
description = "A package template for Rust-based Compute@Edge projects equipped for continuous deployment with GitHub Actions"
authors = ["<d.tangren@gmail.com>"]
language = "rust"
