name: Main

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  codestyle:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: 1.43.0
        targets: wasm32-wasi
        components: rustfmt
    - name: Cache cargo
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        paths: |
          ~/.cargo/registry
          ~/.cargo/git
          target      
    - run: cargo fmt --all -- --check

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: 1.43.0
        targets: wasm32-wasi
        components: clippy
    - name: Cache cargo
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        paths: |
          ~/.cargo/registry
          ~/.cargo/git
          target      
    - run: cargo clippy --all-targets -- -D clippy::all

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: 1.43.0
        targets: wasm32-wasi
    - name: Cache cargo
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        paths: |
          ~/.cargo/registry
          ~/.cargo/git
          target      
    - run: cargo check --all

  deploy:
    if: github.ref == 'refs/heads/master'
    needs: [codestyle, lint, build]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: 1.43.0
        targets: wasm32-wasi
    - name: Cache cargo
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        paths: |
          ~/.cargo/registry
          ~/.cargo/git
          target      
    - name: Setup Fastly CLI
      if: env.FASTLY_API_TOKEN
      uses: softprops/setup-fastly-cli@v1
      env:
        FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
    - name: Deploy
      if: env.FASTLY_API_TOKEN
      run: |
        fastly compute build
        fastly compute deploy
      env:
        FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
 